### ISSUE TITLE
1.1.2及1.1.3均被系統報毒後刪除了

### ISSUE THREAD

**Issue by NeiL978** [sunfkny/genshin-gacha-export#12]
**问题描述**
下載解壓縮後執行，直接被系統攔截刪除了

**系统版本**
Windows10專業版 2004版本 -->

**错误信息**
下載解壓縮後執行，直接被系統攔截刪除了

**附加截图**
![Screenshot - 2021-01-29 00 39 12](https://user-images.githubusercontent.com/19291616/106172004-388eba80-61cd-11eb-8def-3237e222e3cb.png)

**Comment by sunfkny** [comment]
已知问题 https://github.com/sunfkny/genshin-gacha-export/issues/8 ，应该是误杀
建议能直接用py文件就不要用exe
