### ISSUE TITLE
将新纪录追加到已有excel文件而非重新生成

### ISSUE THREAD

**Issue by TheTychoStar** [sunfkny/genshin-gacha-export#13]
**关于哪一项功能**
追加新纪录到已有excel的功能

**功能详情**
Mihoyo限制只能查询6个月记录了，每次重新生成新的就不太开心了。可以考虑增加追加记录的功能？
把API get到数据的最小时间和已有excel记录的最大时间比对，只将大于已有时间的数据append到excel里面。
如果API get到的最小时间 - 已有excel记录最大时间 > 180天，给出警告有可能已有不可找回的遗漏数据。

**附加截图**
无

**Comment by sunfkny** [comment]
https://github.com/sunfkny/genshin-gacha-export/releases/tag/v1.1.15
