### ISSUE TITLE
你好，氪老的常驻祈愿，581页以后就卡住不动了。

### ISSUE THREAD

**Issue by hiarno** [sunfkny/genshin-gacha-export#16]
**问题描述**

**附加截图**
![image](https://user-images.githubusercontent.com/18111070/110896511-bd293880-8336-11eb-9562-84162c1d6cac.png)

**Comment by hiarno** [comment]
![image](https://user-images.githubusercontent.com/18111070/110896618-ecd84080-8336-11eb-8cf5-514e9b02294f.png)

**Comment by sunfkny** [comment]
你这也太离谱了，有可能触发风控了，如果可以的话能否把同一目录下的 config.json 发到我的邮箱 1198355143@qq.com 让我测试一下

**Comment by hiarno** [comment]
{
    "FLAG_CLEAN":false,
    "FLAG_MANUAL_INPUT_URL":false,
    "FLAG_SHOW_REPORT":true,
    "FLAG_USE_CAPTURE":true,
    "FLAG_USE_CONFIG_URL":true,
    "FLAG_USE_LOG_URL":true,
    "FLAG_WRITE_XLSX":true,
    "url":"",
    "verison":"v1.1.17"
}

**Comment by hiarno** [comment]
你是不是搞错了？这个是配置文件啊。

**Comment by sunfkny** [comment]
正常情况应该有缓存url的，既然没有，那就打开历史记录之后，把 `%USERPROFILE%\AppData\LocalLow\miHoYo\原神\`  目录下的 output_log.txt 发给我

**Comment by sunfkny** [comment]
或者也可以打开过抽卡历史记录页面后，用 https://github.com/sunfkny/genshin-gacha-export-js/blob/main/geturl.ps1.txt 的内容复制到 PowerShell 里执行，直接提取

**Comment by hiarno** [comment]
那个是富婆，不懂这些。= =！

**Comment by sunfkny** [comment]
那我编译一个日志更详细的版本再试试？

**Comment by hiarno** [comment]
算了，她说不弄了。。。好像查询到了。估计是风控吧。
