### ISSUE TITLE
1.4版本更新后不停获取常驻祈愿列表

### ISSUE THREAD

**Issue by Smith-Wang** [sunfkny/genshin-gacha-export#17]
![图片](https://user-images.githubusercontent.com/24584213/111415744-82037c80-871d-11eb-8b1c-71139f35f3e9.png)
实际上没抽过这么多呀

**Comment by sunfkny** [comment]
v1.1.18已修复

**Comment by wangzeyu92** [comment]
够速度，我这刚抓包分析出问题
