### ISSUE TITLE
在有1.3的游戏版本老数据情况下，新版本会出现重复抽卡记录

### ISSUE THREAD

**Issue by flewsea** [sunfkny/genshin-gacha-export#18]
**问题描述**

在1.4之前使用过此工具进行导出，使用1.18版本的工具进行导出会出现数据重复

**Comment by sunfkny** [comment]
我这里没有问题，出现重复不太好修啊，只能删掉gachaData-UID.json历史记录，现在好像还能获取到开服的数据的

**Comment by flewsea** [comment]
已经删除重建了，但是看了下数据，貌似现在的数据出现了一个新的key :id导致的

**Comment by sunfkny** [comment]
因为比较重复数据是整个比较的，所以没有考虑到加了一个新key，可行的方法是只用时间和名称，但是还是建议管理好excel，毕竟下个版本说不定api又改了

**Comment by hgjazhgj** [comment]
之后能把每次抓到的json单独存放起来吗  
像这个问题直接把合并好的记录全破坏了

**Comment by sunfkny** [comment]
已经加了，现在会生成本次获取数据单独的 gachaData-{uid}-{time}.json

**Comment by hgjazhgj** [comment]
大佬动作好快...  
刚创建pr发现大佬已经搞定了
