### ISSUE TITLE
如何更新getConfigList.json及gacha_info.json

### ISSUE THREAD

**Issue by NeiL978** [sunfkny/genshin-gacha-export#2]
你好
請問該如何更新這兩個檔案?

**Comment by sunfkny** [comment]
和url一样抓包，Readme里面已经写了
## 卡池和物品数据
getConfigList.json是卡池数据，来自`https://hk4e-api.mihoyo.com/event/gacha_info/api/getConfigList?xxxxxxx`，如果有新卡池就下载替换这个json
gacha_info.json是物品数据，来自`https://webstatic.mihoyo.com/hk4e/gacha_info/cn_gf01/items/zh-cn.json`，如果有新物品就下载替换这个json

**Comment by NeiL978** [comment]
請問
`https://hk4e-api.mihoyo.com/event/gacha_info/api/getConfigList?xxxxxxx`
後面的xxxxxxx是什麼??

**Comment by sunfkny** [comment]
只要是getConfigList就对了，后面都是参数比如authkey之类，下载必须带着参数不然 authkey valid error

**Comment by NeiL978** [comment]
我抓出來的東西是這些 怎麼覺得怪怪的
```
{
  "retcode": 0,
  "message": "OK",
  "data": {
    "gacha_type_list": [
      {
        "id": "4",
        "key": "200",
        "name": "常駐祈願"
      },
      {
        "id": "14",
        "key": "100",
        "name": "新手祈願"
      },
      {
        "id": "15",
        "key": "301",
        "name": "角色活動祈願"
      },
      {
        "id": "16",
        "key": "302",
        "name": "武器活動祈願"
      }
    ],
    "region": "os_asia"
  }
}
```

**Comment by sunfkny** [comment]
没问题，这是卡池id数据，主要是之后新加池子也能遍历各个池子用的
你要的应该是是 [https://webstatic.mihoyo.com/hk4e/gacha_info/cn_gf01/items/zh-cn.json](https://webstatic.mihoyo.com/hk4e/gacha_info/cn_gf01/items/zh-cn.json) 这个不用参数，而且语言可选 
比如繁中 [https://webstatic.mihoyo.com/hk4e/gacha_info/cn_gf01/items/**zh-tw**.json](https://webstatic.mihoyo.com/hk4e/gacha_info/cn_gf01/items/zh-tw.json) 
我把它的文件名改成 gacha_info.json 了

**Comment by NeiL978** [comment]
好的 謝謝
我自己也抓了繁中的改了
