### ISSUE TITLE
数据异常

### ISSUE THREAD

**Issue by ktKongTong** [sunfkny/genshin-gacha-export#21]
**问题描述**

**系统版本**
Windows10 20H2

**错误信息**
新手祈愿数据异常，新手祈愿就出了一个诺艾尔和班尼特

**附加截图**
![image](https://user-images.githubusercontent.com/44502608/111931491-463e2d80-8af6-11eb-95a0-8f559b573010.png)

**Comment by ktKongTong** [comment]
应该是是mihoyo接口限定6个月时间的问题，但是综合概率那儿也不正常

**Comment by sunfkny** [comment]
数据是对的，综合概率不计算右边距上次，所以是1/(10-3)，基础概率则是计算全部所以是1/10

在wiki里有写
```
基础概率和综合概率
基础概率：数量/总抽数
综合概率：数量/上次该星级总抽数
```

**Comment by ktKongTong** [comment]
哦哦，明白了
