### ISSUE TITLE
关于祈愿ID的问题

### ISSUE THREAD

**Issue by Scighost** [sunfkny/genshin-gacha-export#22]
入坑时间比较晚，不知道之前的API是什么情况。
有这么几个问题：

1、服务器返回的祈愿数据中ID这个key是在哪个版本中加入的？
2、您的软件在什么时候增加了保存祈愿ID的功能？
3、之前保存的没有ID的祈愿数据会被补上这一数据？

您的回答对我开发很重要，关系到能否直接从json文件导入数据，非常感谢！

**Comment by sunfkny** [comment]
1，看历史issue应该是1.4更新加入的
2，我没有过滤api返回值，api是什么样就原样保存
3，我测试了通过id递减补全没有id项，来导入你的KeqingNiuza，是可以识别的

**Comment by Scighost** [comment]
我的项目中Id只是用来去重的，我也打算用递增的方法保存导入数据的id
1.4版本后就无法获取6个月之前的记录了，有id的数据和无id的数据是怎么合并的？
上面说的有点绕口，保存的文件中是不是同时存在有id和无id的数据？

**Comment by sunfkny** [comment]
确实存在有ID和无ID两种情况
1.4的这次更新仅使用时间和名称合并
https://github.com/sunfkny/genshin-gacha-export/commit/34705727c0d3a4cf6c8338df8648b4dd2eacc2ba

**Comment by Scighost** [comment]
感谢回答，继续爆肝去了😂
