### ISSUE TITLE
获取部分内容后显示连接失败并弹出

### ISSUE THREAD

**Issue by ginkin** [sunfkny/genshin-gacha-export#23]
**问题描述**

在寻找日志文件中链接合法的情况下，获取祈愿页会突然长时间卡死，之后显示错误信息并直接弹出。多次尝试并不会卡死在同一个位置且无规律。网络环境可以正常观看bilibili直播，且无波动。访问位置在海外，但之前顺利获取并未出现过类似问题。

**系统版本**

Windows10 20H2

**错误信息**

见附件。

**附加截图**
[log.txt](https://github.com/sunfkny/genshin-gacha-export/files/6501472/log.txt)

**Comment by sunfkny** [comment]
看链接你应该是海外玩国服，不排除是对海外IP风控比较严格，我使用报错中的链接无法复现问题
另外我这个工具比较拉跨，网络请求不会走系统的代理，可以试试这两个工具 https://github.com/Scighost/KeqingNiuza   https://github.com/biuuu/genshin-wish-export
