### ISSUE TITLE
在游戏2.3版本新角色祈愿池开启后，角色活动祈愿记录获取失败

### ISSUE THREAD

**Issue by OriLight152** [sunfkny/genshin-gacha-export#26]
**问题描述**
在游戏2.3版本新角色祈愿池开启后，角色活动祈愿记录获取失败

**系统版本**
Windows10 21H1 19043.1348

**错误信息**
![image](https://user-images.githubusercontent.com/61224409/143184036-3742ffe2-7010-49cf-97e3-7c89da34d8a6.png)

**Comment by sunfkny** [comment]
已知问题，只要在每次请求后`sleep(0.5)`就行了

**Comment by SpecterHi** [comment]
主要如果用的是编译好的版本该怎么办啊

**Comment by sunfkny** [comment]
> 主要如果用的是编译好的版本该怎么办啊

等我编译上传（晚点研究一下action自动编译）

**Comment by sunfkny** [comment]
[v1.1.23](https://github.com/sunfkny/genshin-gacha-export/releases/tag/v1.1.23)
