### ISSUE TITLE
规范祈愿记录导出格式

### ISSUE THREAD

**Issue by sunfkny** [sunfkny/genshin-gacha-export#28]
**关于哪一项功能**
祈愿记录导出

**功能详情**
https://github.com/Scighost/KeqingNiuza/issues/53

**Comment by Arondight** [comment]
导出的 execl 无法导入刻记牛杂店，角色2 卡池的记录丢失

**Comment by Lightczx** [comment]
牛杂店 的作者最近比较忙还没更新适配

**Comment by Arondight** [comment]
> @Scighost 最近比较忙还没更新适配

呃，所以是牛杂店滞后了？
