### ISSUE TITLE
不知道为啥突然就打不开QAQ

### ISSUE THREAD

**Issue by euymiannn** [sunfkny/genshin-gacha-export#30]
**问题描述**

打不开，打开秒闪退。
下载的是最新版本的。

**系统版本**

 win10 64位

**错误信息**

**附加截图**
![1f1b57ff675effb810f9e758df7e914](https://user-images.githubusercontent.com/96413383/146736600-6cec4841-4f25-4bb5-a65a-a01749c7307a.png)

**Comment by Lightczx** [comment]
jsdelivr 服务器炸了

**Comment by sunfkny** [comment]
https://www.v2ex.com/t/823281
确实是jsdelivr的问题，我用来检测版本更新的，先加个异常捕获再说，晚点再考虑要不要加其他cdn
