### ISSUE TITLE
突然需要抓包，运行程序后自动抓包报错

### ISSUE THREAD

**Issue by a390138773** [sunfkny/genshin-gacha-export#36]
检查更新中...
检查配置文件中的链接...url为空
检测到国服日志文件
日志文件中没有链接
开始通过抓包模式捕获链接
注意：必须等程序运行结束或者Ctrl+C退出，不要直接关闭，否则会上不了网
可以用解压出来的关闭代理bat脚本恢复，或者 设置 - 网络和Internet - 代理 - 使用代理服务器 - 关闭
确定使用抓包模式吗？输入yes确认执行：yes
设置代理...成功
请打开抽卡记录页面，并翻页几次
正在捕获链接...抓包模块出错:
 Traceback (most recent call last):
  File "main.py", line 442, in <module>
  File "main.py", line 286, in capture
ModuleNotFoundError: No module named 'mitmproxy.proxy.config'

**Comment by sunfkny** [comment]
https://github.com/sunfkny/genshin-gacha-export/actions/runs/1703840073
试一下这个，mitmproxy最新版去除了ProxyServer和ProxyConfig导致报错，降级就好了，当时为了适配win7版本直接没指定依赖版本，py37能用的最新版本是5.3.0是没有问题的，v6就不支持py37了

**Comment by LaoshuBaby** [comment]
我也遇到了一样的问题，而且即使我pip install mitmproxy以后都不行

https://github.com/sunfkny/genshin-gacha-export/releases/tag/v2.4.0.01122052

下载的是这里面的py39版本

（我本地从38到310的py环境都有）

然后找到上次下载的v1.1.32.12241010

一样显示这个错误

（当然更早时期我存下来的release因为不支持双卡池所以我就没打开测试了）

**Comment by sunfkny** [comment]
> **问题描述** 我也遇到了一样的问题，而且即使我pip install mitmproxy以后都不行
> 
> https://github.com/sunfkny/genshin-gacha-export/releases/tag/v2.4.0.01122052
> 
> 下载的是这里面的py39版本
> 
> （我本地从38到310的py环境都有）
> 
> 然后找到上次下载的v1.1.32.12241010
> 
> 一样显示这个错误
> 
> （当然更早时期我存下来的release因为不支持双卡池所以我就没打开测试了）
> 
> **系统版本** Windows 11 Insider Preview Build 22543
> 
> **错误信息**
> 
> ```
> 检查更新中...
> 检查更新失败
> 检查配置文件中的链接...url为空
> 检测到国服日志文件
> 日志文件中没有链接
> 开始通过抓包模式捕获链接
> 注意：必须等程序运行结束或者Ctrl+C退出，不要直接关闭，否则会上不了网
> 可以用解压出来的关闭代理bat脚本恢复，或者 设置 - 网络和Internet - 代理 - 使用代理服务器 - 关闭
> 确定使用抓包模式吗？输入yes确认执行：yes
> 设置代理...成功
> 请打开抽卡记录页面，并翻页几次
> 正在捕获链接...抓包模块出错:
>  Traceback (most recent call last):
>   File "main.py", line 442, in <module>
>   File "main.py", line 286, in capture
> ModuleNotFoundError: No module named 'mitmproxy.proxy.config'
> ```
> 
> **附加截图**
> 
> 略

`pip install mitmproxy==5.3.0`
代码没适配 v6，改成5.3.0的 https://github.com/sunfkny/genshin-gacha-export/commit/14298806738d08b3a8d1e668153dad7098905832 还没release

**Comment by LaoshuBaby** [comment]
> `pip install mitmproxy==5.3.0`
> 代码没适配 v6，改成5.3.0的 [1429880](https://github.com/sunfkny/genshin-gacha-export/commit/14298806738d08b3a8d1e668153dad7098905832) 还没release

谢谢
刚刚进行了如下操作

1. cmd管理员权限运行如上命令
2. 下载了https://github.com/sunfkny/genshin-gacha-export/actions/runs/1810731552 中的最新版本（非win7的capture版本）并把旧抽卡记录放进目录
3. 关闭clash/ssr之类工具
4. 确定可以使用并且抓到的数据大致看起来正常，体验良好


再次感谢作者的新feature维护和耐心解答

**Comment by sunfkny** [comment]
> 我又来了，使用最新版（自动更新的）会提示这样的错误：？
> 
> ```
> 2022-04-19 22:04:14.322 | ERROR    | __main__:<module>:338 - 抓包模块出错: Traceback (most recent call last):
>   File "main.py", line 333, in <module>
>   File "capture.py", line 51, in capture
>   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
>   File "mitmproxy\tools\dump.py", line 1, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
>   File "mitmproxy\addons\__init__.py", line 12, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
>   File "mitmproxy\addons\onboarding.py", line 2, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
>   File "mitmproxy\addons\onboardingapp\__init__.py", line 3, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
>   File "flask\__init__.py", line 14, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
>   File "jinja2\__init__.py", line 12, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
>   File "jinja2\environment.py", line 25, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
>   File "jinja2\defaults.py", line 3, in <module>
>   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
>   File "jinja2\filters.py", line 13, in <module>
> ImportError: cannot import name 'soft_unicode' from 'markupsafe' (C:\Users\快乐的~1\AppData\Local\Temp\_MEI112202\markupsafe\__init__.pyc)
> ```
> 
> ![图片](https://user-images.githubusercontent.com/42690037/164022765-ac3b0ec8-d6ec-486b-abf0-ced993faa320.png)
> 
> 感觉本项目天天斗智斗勇的中心就是抓包模块呢（逃）
> 
> 依然是pip install了这个markupsafe也无济于事
> 
> 我再试试自行处理一下，这里权作记录
> 
> 比较迷惑的是这个明明是在[v2.5.0.02221942](https://github.com/sunfkny/genshin-gacha-export/releases/tag/v2.5.0.02221942)中说修复过了，但是现在我使用v2.6.0.04181243依然会遇到
> 
> 按照release的issue找到`MarkupSafe==2.0.1`，安装该版本一样会出问题

你这是PyInstaller运行，自己装pip当然没用

没找到 mitmproxy 5.3.0（win7只能这个版本）替代抓包方案就不能删 `MarkupSafe==2.0.1` ，我忘记了这个问题吧锁定版本删了 ，在重新打包了 https://github.com/sunfkny/genshin-gacha-export/actions/runs/2190233569
