### ISSUE TITLE
不应该根据 config 中的版本进行更新检测

### ISSUE THREAD

**Issue by Yinr** [sunfkny/genshin-gacha-export#38]
**问题描述**

目前检测更新过程通过 `config.json` 来判断当前版本，这会出现以下问题：
* 更新时不能直接简单将新文件覆盖旧文件更新，会导致设置丢失
* 版本信息容易被误修改导致检测更新结果异常

希望可以将版本号直接记录到程序中，或者分离出一个文件记录版本号。

**Comment by sunfkny** [comment]
确实，还是在程序中写死吧，顺便还可以考虑加上配置文件出错/丢失自动生成一个`config.json`的功能

**Comment by Yinr** [comment]
嗯嗯。我觉得应该在发布文件中去除 `config.json`，在程序运行时如果不存在就自动生成。
这样更新的时候可以直接整个压缩包解压到当前文件夹就行了。

**Comment by n12z** [comment]
![image](https://user-images.githubusercontent.com/39026577/152370977-b47ea338-c45d-4961-b5d9-1083b06883a6.png)
老是卡在检查版本更新。
