### ISSUE TITLE
关于使用UIGF导入别的软件出现数据错误的问题

### ISSUE THREAD

**Issue by RyanYao6** [sunfkny/genshin-gacha-export#39]
**问题描述**

使用新版本v2.4.0.01122052导出数据，将UIGF导入到刻记牛杂店和SnapGenshin会出现数据混乱。

**系统版本**

Windows11 21H2

**错误信息**

首先感谢作者大佬，之前一直在使用你的这款软件。从老版本一直用到v1.1.23这个版本，最近看到新版本支持UIGF可以导入到别的软件，就想着试试，结果就出现此问题。

**附加截图**
v1.1.23
![v1 1 23](https://user-images.githubusercontent.com/98397469/150983458-14fdac6b-b113-497f-a44d-955d5414a301.png)
v2.4.0
![v2 4 0 01122052](https://user-images.githubusercontent.com/98397469/150983529-84764fad-43ec-4cf2-9c17-53324eca5555.png)
导入刻记牛杂店出现数据位置错误
![刻](https://user-images.githubusercontent.com/98397469/150983796-6b673076-212a-467d-af36-64ec50f590d9.png)
![刻2](https://user-images.githubusercontent.com/98397469/150983827-4f21cbd9-d013-437f-8412-7f60d3007b12.png)
v2.4.0导出的Excel表格中的原始数据好像没按时间正确排序
![原始数据](https://user-images.githubusercontent.com/98397469/150984195-58b2d40a-de30-4275-822c-e2f9b6a4465b.png)

**附带数据文件**
v1.1.23
[v1.1.23.zip](https://github.com/sunfkny/genshin-gacha-export/files/7933833/v1.1.23.zip)
v2.4.0
[v2.4.0.zip](https://github.com/sunfkny/genshin-gacha-export/files/7933842/v2.4.0.zip)

**Comment by sunfkny** [comment]
看一下这样对了吗，我确实忘记给时间排序了，因为我所有记录都有id，所以没测试出来这个问题
[gachaExport-20220125230719.xlsx](https://github.com/sunfkny/genshin-gacha-export/files/7934671/gachaExport-20220125230719.xlsx)
![image](https://user-images.githubusercontent.com/30853461/151003379-c753b18d-24f1-4c6f-ad0d-8d3f297f15d4.png)

**Comment by RyanYao6** [comment]
显示五星的顺序是没问题了，不过我看数据里面还有几段时间顺序不对是正常的吗？













原始邮件



发件人："sunfkny"< ***@***.*** &gt;;

发件时间：2022/1/25 23:13

收件人："sunfkny/genshin-gacha-export"< ***@***.*** &gt;;

抄送人："ryan2509"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [sunfkny/genshin-gacha-export] 关于使用UIGF导入别的软件出现数据错误的问题 (Issue #39)







看一下这样对了吗，我确实忘记给时间排序了，因为我所有记录都有id，所以没测试出来这个问题
gachaExport-20220125230719.xlsx


&amp;mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by RyanYao6** [comment]
> 看一下这样对了吗，我确实忘记给时间排序了，因为我所有记录都有id，所以没测试出来这个问题 [gachaExport-20220125230719.xlsx](https://github.com/sunfkny/genshin-gacha-export/files/7934671/gachaExport-20220125230719.xlsx) ![图像](https://user-images.githubusercontent.com/30853461/151003379-c753b18d-24f1-4c6f-ad0d-8d3f297f15d4.png)

显示五星的顺序是没问题了，不过我看数据里面还有几段时间顺序不对是正常的吗？

**Comment by RyanYao6** [comment]
![QQ截图20220125234700](https://user-images.githubusercontent.com/98397469/151010050-de50bf95-3614-4490-b8b3-5605c77c87b8.png)
比如这个地方从2021突然跳回2020是正常的吗

**Comment by Lightczx** [comment]
换池子了这样是可以的，正常的

**Comment by RyanYao6** [comment]
哦，好的。

**Comment by RyanYao6** [comment]
嗯，好的。代码方面我也不太懂，能解决这个BUG就好，谢谢大佬。
