### ISSUE TITLE
URL失效解决方案

### ISSUE THREAD

**Issue by HuanLinMaster** [sunfkny/genshin-gacha-export#47]
**问题描述**

url失效
![ZT_PCRSR ZW_DY9H74Z$3TU](https://user-images.githubusercontent.com/94176676/163661845-be489f13-44d3-4fd7-8e45-96aaedc79c29.png)

**系统版本**

所有版本

**错误信息**

main.py 原api已失效
请将main.py 324 325行中的OnGetWebViewPageFinish替换为OnGetBeforeNavigationMessage

**附加截图**
无

**Comment by sunfkny** [comment]
`OnGetBeforeNavigationMessage` 和 `OnGetWebViewPageFinish` 的链接是一样的
![image](https://user-images.githubusercontent.com/30853461/163662104-b8bbaca6-7faf-4ce2-87e6-b4412c2cef96.png)
看你日志是 authkey error, 一般是链接过期了
