### ISSUE TITLE
抽卡记录导出工具出错

### ISSUE THREAD

**Issue by 981537091** [sunfkny/genshin-gacha-export#5]
**问题描述**

初次运行exe时在【开始捕获链接】处卡主，然后运行了附带的bat关闭代理并重新启动exe后出现error提示。

**系统版本**

Windows10

**错误信息**

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Traceback (most recent call last):
  File "mitmproxy\proxy\server.py", line 121, in handle
TypeError: 'NoneType' object is not callable

**附加截图**
![屏幕截图 2021-01-25 193248](https://user-images.githubusercontent.com/77967908/105700682-24845800-5f44-11eb-90ca-8adaf9a181fe.png)

**Comment by sunfkny** [comment]
https://github.com/sunfkny/genshin-gacha-export/releases/tag/v1.1.1-dev
麻烦用这个测试版本看看具体报错

**Comment by sunfkny** [comment]
https://github.com/sunfkny/genshin-gacha-export/releases/tag/v1.1.2-dev
