### ISSUE TITLE
新版本导出和旧版不一样

### ISSUE THREAD

**Issue by MY36** [sunfkny/genshin-gacha-export#50]
**问题描述**
新版本导出和旧版不一样

[**系统版本**](url)

**错误信息**
新版本导出和旧版不一样

**附加截图**
旧版本
![屏幕截图 2022-05-09 204543](https://user-images.githubusercontent.com/82233042/167413123-cd973414-f5dc-4359-b719-e658c6302542.png)
新版本
![屏幕截图 2022-05-09 204458](https://user-images.githubusercontent.com/82233042/167413210-fab05f33-1500-4bbf-975f-fd87415b64d1.png)

**Comment by sunfkny** [comment]
修改了逻辑，顺序反了，已重传
