### ISSUE TITLE
v2.6.0.05091700 出货抽数统计有问题

### ISSUE THREAD

**Issue by oTnTh** [sunfkny/genshin-gacha-export#51]
1、将4月备份的文件复制出来，重命名为gachaData.json和gachaData-[UID].json
2、执行v2.6.0.05091700，导出新数据

问题：

常驻池跟角色限定池的总抽数都是对的，但是“距上次”、“平均出货次数”，以及每一个五星多少抽的数据，都是错的。

另外，导出的UIGF文件没有数据：`"list": []`

回退至v2.6.0.04301038，再次尝试，导出数据正常了。

**Comment by sunfkny** [comment]
可以上传一下日志和gachaData-[UID].json吗，另外最好重新下载最新版本试一下

**Comment by oTnTh** [comment]
我直接用仓库里的代码试了一下，生成的gachaReport.html正常了，要不你等等再发布一个吧。

UIGF的问题，main.py的91行写错了：

`IGF_data = UIGF_converter.convert(uid, mergeData)`

应该是：

`IGF_data = UIGF_converter.convert(uid, mergeData["gachaLog"])`

**Comment by sunfkny** [comment]
应该只是后面处理的时候出的问题
https://github.com/sunfkny/genshin-gacha-export/commit/02fce62160033484edafc5d6bbe2e062a4b97920#diff-5b204315d3ac3dab4f9ae3699638d572de3443564b19d3a80dc4c9558480592aL38 这里多删了，本地数据其实还在，我直接
```
if "gachaLog" in gachaLog:
    gachaLog = gachaLog["gachaLog"]
```
吧两种情况都考虑上吧

**Comment by oTnTh** [comment]
我试了一下，v2.7.0.06020731看起来没啥问题，辛苦啦。
