### ISSUE TITLE
请问我旧版本升级新版本后，可以导出包含所有记录的UIFG格式EXCLE吗？还是只能有6个月的？

### ISSUE THREAD

**Issue by DomineeringDragon** [sunfkny/genshin-gacha-export#53]
不知道为什么只能提BUG反馈，不好意思！
请问我旧版本升级新版本后，可以导出包含所有记录的UIFG格式EXCLE吗？还是只能有6个月的？

**Comment by sunfkny** [comment]
请仔细阅读Readme
> 将获取到的6个月历史记录与本地记录合并（1.3版本更新后api只能获取6个月历史记录）  
> 导出抽卡记录为 json 和 excel (已适配 UIGF 格式)
