### ISSUE TITLE
3.0版本 读取日志功能失效 只能使用抓包模式

### ISSUE THREAD

**Issue by sunfkny** [sunfkny/genshin-gacha-export#55]
原神更新 3.0 之后，日志里没有链接，手机断网法看不到链接，只能用抓包模式

**Comment by Small-Ku** [comment]
國際服的 URL 域名貌似改成 hoyoverse.com/event/gacha_info/api/getGachaLog 了

**Comment by sunfkny** [comment]
> 國際服的 URL 域名貌似改成 hoyoverse.com/event/gacha_info/api/getGachaLog 了

好的，已经改成匹配 path `/event/gacha_info/api/getGachaLog`  了

**Comment by MeisterZH** [comment]
抓包模式也不行，是因为我在国外的原因么

**Comment by sunfkny** [comment]
> 抓包模式也不行，是因为我在国外的原因么

关代理/加速器，或者8889端口被占用，换个端口

**Comment by MeisterZH** [comment]
> > 抓包模式也不行，是因为我在国外的原因么
> 
> 关代理/加速器，或者8889端口被占用，换个端口
换什么呢 8080？ 我是从国外裸连的 没开加速器

**Comment by wsq-source** [comment]
点那个rootCert.fpx需要私钥密码怎么办

**Comment by wsq-source** [comment]
历史记录翻页的时候提示”数据获取失败，检查网络重试“

**Comment by YChenJ** [comment]
3.0可以正常导出，不过我之前一直用的老版本，导出的文档没法和新的合并怎解

**Comment by icyzeroice** [comment]
https://feixiaoqiu.com/rank_url_upload_init/ 非小酋这里有写一种新的从日志导出 URL 的方式，现在 3.0 也可以了
