### ISSUE TITLE
Windows 11、3.0版本抓包崩溃

### ISSUE THREAD

**Issue by perqin** [sunfkny/genshin-gacha-export#56]
**问题描述**

1. 从Coding下载最新包（genshin-gacha-export_capture.zip，v3.0.0.08251149）
2. 运行CaptureApp.exe
3. 允许安装证书、防火墙放行
4. 点击“开始”
5. 切回原神抽卡记录页面，点击下一页
6. 提示网络错误，此时按Windows回到桌面发现CaptureApp窗口消失，应该是崩溃了

尝试过修改端口，仍然复现。

**系统版本**

Windows 11专业版21H2

**错误信息**

直接崩溃，无错误弹窗。

**附加截图**
无

**Comment by sunfkny** [comment]
看看你的剪贴板，默认获取到链接后复制到剪贴板并自动退出



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月2日(周五) 晚上6:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [sunfkny/genshin-gacha-export] Windows 11、3.0版本抓包崩溃 (Issue #56)




 
问题描述
  
从Coding下载最新包（genshin-gacha-export_capture.zip，v3.0.0.08251149）
 
运行CaptureApp.exe
 
允许安装证书、防火墙放行
 
点击“开始”
 
切回原神抽卡记录页面，点击下一页
 
提示网络错误，此时按Windows回到桌面发现CaptureApp窗口消失，应该是崩溃了
  
尝试过修改端口，仍然复现。
 
系统版本
 
Windows 11专业版21H2
 
错误信息
 
直接崩溃，无错误弹窗。
 
附加截图
 无

**Comment by perqin** [comment]
私密马赛，我没看到“自动复制到剪切板并退出”的勾选框，打扰了（
