### ISSUE TITLE
日志读取模块出错

### ISSUE THREAD

**Issue by MY36** [sunfkny/genshin-gacha-export#58]
**问题描述**
3.0更新3.1后
**系统版本**
Windows11 21H2

**错误信息**
ERROR    | __main__:<module>:352 - 日志读取模块出错: Traceback (most recent call last):
  File "main.py", line 301, in <module>
  File "pathlib.py", line 1267, in read_text
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 475910: invalid start byte

**附加截图**

**Comment by chizukicn** [comment]
同样是日志读取错误，更新到10月2日的版本就出现了这个错误
![image](https://user-images.githubusercontent.com/16945858/199407453-1ceea2b0-aa99-4465-aed4-7f9be7cd3d7b.png)
将"用户\AppData\LocalLow\miHoYo\原神\output_log.txt"这个文件用utf-8重新保存一次就好了

**Comment by sunfkny** [comment]
909e75419750ac3dadd7c4aafbd5312e8d61cc3c
