### ISSUE TITLE
error cannot find module fs/promises

### ISSUE THREAD

**Issue by RyoShigure** [sunfkny/genshin-gacha-export#67]
**问题描述**
使用抽卡工具已經很久了,第一次報這類型的錯誤
我點了下抽卡工具更新,然後就突然不能用了,在報錯後自己有嘗試過修復Node和重裝JAVA,都沒用

**系统版本**
WIN10 64bit

**错误信息**
error cannot find module fs/promises

**附加截图**

![QQ图片20230707092930](https://github.com/sunfkny/genshin-gacha-export/assets/138836203/e65cbba3-2187-4594-9ebb-de293c14f216)

> 

![QQ截图20230707094914](https://github.com/sunfkny/genshin-gacha-export/assets/138836203/ef65ffd9-ab1b-4a7b-a777-7d27052d8d05)
NGA也有人反饋報錯
>

**Comment by TheLZY** [comment]
我也是，点了更新之后就出现这个

**Comment by sunfkny** [comment]
找错项目了吧，https://github.com/biuuu/genshin-wish-export/ 这个才是electron的，之前确实叫 genshin-gacha-export ，后来他改名了
