### ISSUE TITLE
无法正常导出

### ISSUE THREAD

**Issue by ainopara** [sunfkny/genshin-gacha-export#68]
**问题描述**
尝试导出会提示 key 过期

**错误信息**
原因是新版本中 webCache 的存储路径有变化，同时旧路径下的缓存文件也没有被删除，导致工具一直在使用早已过期的 cache 文件获取 key
[其他同类项目的处理方式](https://github.com/biuuu/genshin-wish-export/commit/50d4897cf82ddd523ae068efe1804b4110a90c1c)

**Comment by sunfkny** [comment]
fix [188a55a](https://github.com/sunfkny/genshin-gacha-export/commit/188a55acf3e1c73ef1c493122d5ea5b167606678)
