### ISSUE TITLE
抽卡服务器似乎改了API了

### ISSUE THREAD

**Issue by LaoshuBaby** [sunfkny/genshin-gacha-export#72]
**问题描述**

已经抓不到了

**系统版本**

**错误信息**

`/event/gacha_info/api/getGachaLog`正则去掉以后直接抓，可以抓到一个 `https://public-operation-hk4e.mihoyo.com/gacha_info/api/getGachaLog?` 的链接，而不是以前常见的 `https://hk4e-api.mihoyo.com/event/gacha_info/api/getGachaLog` （感谢UIGF群友）

**附加截图**
![图片](https://github.com/sunfkny/genshin-gacha-export/assets/42690037/411f7882-300e-4bd5-a86a-c17aa1b7eee9)

**Comment by Streamer-stars** [comment]
+1，4.2版本更新后就抓不到了

**Comment by LaoshuBaby** [comment]
> +1，4.2版本更新后就抓不到了

你试试在这个抓取器里面把url包含删掉，看看能不能抓到新的url

**Comment by sunfkny** [comment]
https://github.com/sunfkny/genshin-gacha-export/releases/tag/v4.2.0.11092107

**Comment by LaoshuBaby** [comment]
@sunfkny  又变了

可以直接看 https://github.com/MadeBaruna/paimon-moe/issues/555 里面的记载，有各个友商针对这一变化的commit

**Comment by sunfkny** [comment]
@LaoshuBaby  这个项目 https://github.com/sunfkny/genshin-gacha-export/commit/ebe3cddab3af5da1a4602d2b36b1817a1f9f8f22 和 Snap.Hutao https://github.com/DGP-Studio/Snap.Hutao/commit/3eb255639304474d6dd92ba9ccea0c82645e48cc 4.2就改了

**Comment by LaoshuBaby** [comment]
哎，是喔！(是我来迟了嘿嘿(派蒙流口水.JPG))
