### ISSUE TITLE
新版本更新后报错

### ISSUE THREAD

**Issue by yongyeqc** [sunfkny/genshin-gacha-export#74]
**问题描述**

原神4.2版本更新后，每次使用都显示 云·原神日志不存在 ，一般都靠抓包来完成。
这次更新后就直接报错了

**系统版本**

**错误信息**

日志读取模块出错: Traceback (most recent call last):
  File "main.py", line 317, in <module>
AssertionError: 未找到游戏路径

**附加截图**
![image](https://github.com/sunfkny/genshin-gacha-export/assets/151020632/1298213e-123a-4c4b-a110-d3d3ae4a125b)

**Comment by sunfkny** [comment]
未找到游戏路径才是重点, 上传一下 `output_log.txt`

**Comment by yongyeqc** [comment]
> 未找到游戏路径才是重点, 上传一下`output_log.txt`

**Comment by yongyeqc** [comment]
> > 未找到游戏路径才是重点, 上传一下`output_log.txt`

这个是哪个文件？
是这个吗
[log.txt](https://github.com/sunfkny/genshin-gacha-export/files/13376753/log.txt)

**Comment by sunfkny** [comment]
2023-11-16 17:41:29.925 | INFO     | __main__:<module>:301 - 使用日志 C:\Users\admin\AppData\LocalLow\miHoYo\原神\output_log.txt

**Comment by yongyeqc** [comment]
[output_log.txt](https://github.com/sunfkny/genshin-gacha-export/files/13377282/output_log.txt)

**Comment by sunfkny** [comment]
看日志门都没开就退出了, 自然找到不到游戏路径, 使用缓存文件的方式必须完整启动游戏才行

**Comment by yongyeqc** [comment]
原神我今天没有启动过，那个是昨天的日志。
我当时开着云·原神的记录，我是想通过云·原神的日志来读取祈愿记录，而4.2之后似乎就不能读取云·原神的日志文件了，或者有没有什么方法可以跳过原神的日志文件这步直接用抓包的方式获取

**Comment by sunfkny** [comment]
参考 [wiki ](https://github.com/sunfkny/genshin-gacha-export/wiki/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6) , 把 `config.json` 配置文件中的 `"FLAG_USE_LOG_URL":true,` 改为 `"FLAG_USE_LOG_URL":false,` 就可以关闭使用原神日志获取链接了

 云·原神日志不存在是因为文件路径变了,待会更新一个版本
