### ISSUE TITLE
读取抽卡记录读到一半报错

### ISSUE THREAD

**Issue by yongyeqc** [sunfkny/genshin-gacha-export#75]
### 版本

v4.5.0.03131957

### 错误信息

就正常使用，打开游戏打开抽卡记录，再打开genshin-gacha-export.exe。
（缓存文件data_2 上传不了，加了个后缀记得删一下）

### 诊断日志

[log.txt](https://github.com/user-attachments/files/15839663/log.txt)
[data_2.txt](https://github.com/user-attachments/files/15839666/data_2.txt)

**Comment by yongyeqc** [comment]
之前也遇到过一次，试了3次成功了，当时没留log.txt，就没报

**Comment by sunfkny** [comment]
看日志是网络问题，管理员权限执行 `netsh winsock reset` 重启再试试

**Comment by yongyeqc** [comment]
执行完重启还是报错。好像还是一样的问题
[log.txt](https://github.com/user-attachments/files/15846370/log.txt)
