### ISSUE TITLE
1.1.1 release版本 windows安全中心识别为病毒

### ISSUE THREAD

**Issue by qcb111** [sunfkny/genshin-gacha-export#8]
**问题描述**
1.1.1 release版本 windows安全中心识别为病毒并直接删除
1.1.1-dev 无此问题

**系统版本**
windows10 2004 (build 19041.746)

**错误信息**

**附加截图**
![image](https://user-images.githubusercontent.com/35689435/105731407-57414700-5f6a-11eb-9a3a-e809b4522a47.png)

**Comment by sunfkny** [comment]
https://r.virscan.org/language/zh-cn/report/b8e4c70b332fc1b300f402b54e89b0d2
这个问题太玄学了，virscan没报毒啊
